name:                hraylib3d
version:             0.1.0.0
github:              "githubuser/hraylib3d"
license:             BSD3
author:              "Miles J. Litteral"
maintainer:          "mandaloe2@example.com"
copyright:           "2023 Miles J. Litteral"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/hraylib3d#readme>

dependencies:
- base  >= 4.7 && < 5
- mtl
- aeson
- directory
- binary
- hashable
- JuicyPixels
- unordered-containers
- bytestring
- vect
- vector
- transformers
- pretty-show
- deepseq
- zlib
- filepath
- linear                 #This will replace both vect and Vector, or Vector will do so
- mersenne-random-pure64 #wtf XD, it's from 2008 but maybe that's okay because it's RNG
- data-binary-ieee754    #wtf x2, atleast its an IEEE standard
- elerea                 # ??? DCT? DWT? FRP??? Signals??? https://hackage.haskell.org/package/elerea-2.9.0/docs/FRP-Elerea-Param.html#t:Signal
- megaparsec
- parsec
- containers
- scientific
- microlens-platform
- time
- process
- postgresql-simple
- text
- uuid
- lens
- http-client
- modern-uri
- req
- stm
- digest
- utf8-string
- HaTeX
- OpenGLRaw
- GLFW-b 
#- sdl2
#- vulkan-api
- vulkan
- vulkan-utils
- proteaaudio
- MonadRandom
- attoparsec
#- graphql
#- lambdacube-core  #all the Utils when they inevitably become their own modules (hruby and nsis go here )
- lambdacube-compiler
- lambdacube-ir
- lambdacube-gl
#- lambdacube-xr 
#- lambdacube-vulkan
#- lambdacube-metal
#- lambdacube-renderer # obligatory
- gltf-loader
- gltf-codec
- language-glsl # move to core
- extra
- prettyclass
- base64-bytestring
#- language-vulkan
#- language-metal
#- lambdacube-sl # can entail all shader dialect stuff (including Q3SS)
- data-default
- megastore # move to core
- monomer
- tinyfiledialogs
- adjunctions
- wreq # will be replaced with internal Network module features, currently in for compatibility 
- text-show
- criterion
- nsis

ghc-options:
- -Wall
# - -shared
# - -fno-shared-implib
- -optl-mconsole
- -optl-mwindows
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:  src
  #include-dirs: cbits
  # install-includes:
  #   - stb_image.h
  # c-sources:
  #   - cbits/stb_image.c 
  cc-options:
    - -fPIC
  #extra-include-dirs:  C:\ghcup\msys64\mingw64\include\SDL2
  build-tools:     c2hs

executables:
  hraylib3d:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

  # These all require a class of Widgets and Logic Objects (Components) to represent Script Objects
  # Attached to Entities and even the UI itself
  RealmViewer-FE-Demo:
    main:                Main.hs
    source-dirs:         app/RealmViewer-FE-Demo/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

  RealmBuilder-FE-Demo:
    main:                Main.hs
    source-dirs:         app/RealmBuilder-FE-Demo/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

  RB-ProjectManager-FE-Demo:
    main:                Main.hs
    source-dirs:         app/RB-ProjectManager-FE-Demo/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

  RealmModelViewer-Demo:
    main:                Main.hs
    source-dirs:         app/RealmModelViewer-Demo/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

tests:
  hraylib3d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d
    - sdl2