name:                hraylib3d
version:             0.1.0.0
github:              "githubuser/hraylib3d"
license:             BSD3
author:              "Miles J. Litteral"
maintainer:          "mandaloe2@example.com"
copyright:           "2023 Miles J. Litteral"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/hraylib3d#readme>

dependencies:
- base  >= 4 && <= 5
- mtl
- aeson == 2.1.2.1
- exceptions
- directory
- binary
- hashable
- JuicyPixels
- unordered-containers
- bytestring
- vect
- vector
- transformers
- pretty-show
- deepseq
- zlib
- template-haskell
- filepath
- linear                 #This will replace both vect and Vector, or Vector will do so
- mersenne-random-pure64 #wtf XD, it's from 2008 but maybe that's okay because it's RNG
- data-binary-ieee754    #wtf x2, atleast its an IEEE standard
- elerea                 # ??? DCT? DWT? FRP??? Signals??? https://hackage.haskell.org/package/elerea-2.9.0/docs/FRP-Elerea-Param.html#t:Signal
- megaparsec
- parsec
- containers
- scientific
- microlens-platform
- time
- process
- postgresql-simple
- text
- uuid
- xml
- xml-conduit-writer 
- xml-conduit
- yaml
- lens
- http-client
- modern-uri
- req
- stm
- split
- digest
- utf8-string
- HaTeX
- OpenGLRaw
# Window System Libs
- GLFW-b 
- sdl2
- vulkan     # pick one
- vulkan-api # pick one
- vulkan-utils
- monad-logger
# End Window System
- proteaaudio
- MonadRandom
- attoparsec
- data-default-class
- ilist
- lambdacube-compiler
- lambdacube-ir
- lambdacube-gl
#- lambdacube-metal
#- lambdacube-directx
- gltf-loader
- gltf-codec
- dlist
- wavefront
- network
#- unix
- extra
- prettyclass
- base64-bytestring
- linear-base
- uuid
- data-default
- megastore # move to core
- monomer
- tinyfiledialogs
- adjunctions
- wreq   # will be replaced with internal Network module features, currently in for compatibility 
- http-types
- text-show
- criterion
- monomer-hagrid
- nsis
- hruby

ghc-options:
- -Wall
# - -shared
# - -fno-shared-implib
- -optl-mconsole
- -optl-mwindows
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:  src
  cc-options:
    - -fPIC
  build-tools:  c2hs

  #include-dirs: cbits
  # install-includes:
  #   - stb_image.h
  # c-sources:
  #   - cbits/stb_image.c 
  #https://www.sasaprolic.com/2022/11/statically-linked-binaries-with-haskell.html
  #extra-include-dirs:  C:\ghcup\msys64\mingw64\include\SDL2

#WRAYLIB needs to make DLLs, check out these links to this interest
#https://downloads.haskell.org/~ghc/5.04.1/docs/html/users_guide/win32-dlls-create.html
#https://downloads.haskell.org/~ghc/7.8.3/docs/html/users_guide/win32-dlls.html

executables:
  hraylib3d:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

  # These all require a class of Widgets and Logic Objects (Components) to represent Script Objects
  # Attached to Entities and even the UI itself
  RealmViewer-FE-Demo:
    main:                Main.hs
    source-dirs:         app/RealmViewer-FE-Demo/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d

tests:
  hraylib3d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hraylib3d
    - sdl2