env:
    - TEST_PART=CORE1
    - TEST_PART=CORE2
    - TEST_PART=PROFILING
    - TEST_PART=GHCJS

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - build-essential
            - cabal-install-2.4
            - ghc-8.6.3
            - alex-3.1.7
            - happy-1.19.5

before_install:
    - nvm install 10
    - export PATH=$PWD/.cabal-sandbox/bin:$HOME/.cabal/bin:/opt/ghc/8.6.3/bin:/opt/cabal/2.4/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
    - export

install:
    - travis_retry cabal update
    - ./utils/makePackages.sh
    - ./utils/makeSandbox.sh
    - cabal install -j1 --only-dependencies --enable-tests --enable-benchmarks
    - cabal install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"
    - ghcjs --version
    - ghcjs-boot --version
    - ./test/runTravis.sh boot
    - ghcjs-pkg list

script:
    - ./test/runTravis.sh test

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true

sudo: false
